### ISSUE TITLE
哥你是真的强

### ISSUE THREAD

**Issue by iamwangyabin** [yokonsan/civitai-analysis#1]
我想问几个小问题
就是能不能取消爬sfw
还有就是怎么才能把图片下载下来

只是用于学习研究

**Comment by yokonsan** [comment]
> 我想问几个小问题 就是能不能取消爬sfw 还有就是怎么才能把图片下载下来
> 
> 只是用于学习研究


很简单啊，把请求参数改nsfw就行了
自己动手，丰衣足食
