### ISSUE TITLE
现在是不能爬了？

### ISSUE THREAD

**Issue by lxy2017** [yokonsan/civitai-analysis#2]
我运行代码得到的结果是这样
Fetch json: https://civitai.com/api/trpc/image.getInfinite?input=%7B%22json%22%3A%20%7B%22period%22%3A%20%22AllTime%22%2C%20%22browsingMode%22%3A%20%22SFW%22%2C%20%22sort%22%3A%20%22Most%20Reactions%22%2C%20%22cursor%22%3A%20383018%7D%2C%20%22meta%22%3A%20%7B%22values%22%3A%20%7B%22cursor%22%3A%20%5B%22bigint%22%5D%7D%7D%7D
None
没有东西爬下来

**Comment by yokonsan** [comment]
> 我运行代码得到的结果是这样 Fetch json: https://civitai.com/api/trpc/image.getInfinite?input=%7B%22json%22%3A%20%7B%22period%22%3A%20%22AllTime%22%2C%20%22browsingMode%22%3A%20%22SFW%22%2C%20%22sort%22%3A%20%22Most%20Reactions%22%2C%20%22cursor%22%3A%20383018%7D%2C%20%22meta%22%3A%20%7B%22values%22%3A%20%7B%22cursor%22%3A%20%5B%22bigint%22%5D%7D%7D%7D None 没有东西爬下来

main.py 文件中 `cursor = 383018` 值改 0 试试呢。

**Comment by lxy2017** [comment]
> > 我运行代码得到的结果是这样 Fetch json: https://civitai.com/api/trpc/image.getInfinite?input=%7B%22json%22%3A%20%7B%22period%22%3A%20%22AllTime%22%2C%20%22browsingMode%22%3A%20%22SFW%22%2C%20%22sort%22%3A%20%22Most%20Reactions%22%2C%20%22cursor%22%3A%20383018%7D%2C%20%22meta%22%3A%20%7B%22values%22%3A%20%7B%22cursor%22%3A%20%5B%22bigint%22%5D%7D%7D%7D None 没有东西爬下来
> 
> main.py 文件中 `cursor = 383018` 值改 0 试试呢。

可以了哈，谢谢

**Comment by lxy2017** [comment]
请教下，获取到的json信息的url 不是完整的图像链接，要怎么才能得到这个图像？ 
<img width="511" alt="image" src="https://github.com/yokonsan/civitai-analysis/assets/9693098/5e5182a4-4c0e-477d-a836-407ed600152a">

**Comment by yokonsan** [comment]
> 

你看下图片url地址呢，我记得这个就是做下简单的拼接就行
