### ISSUE TITLE
抓取失败 不能用了 

### ISSUE THREAD

**Issue by 1229064537** [yokonsan/civitai-analysis#3]
{"error":{"json":{"message":"Please use the public API instead: https://github.com/civitai/civitai/wiki/REST-API-Reference","code":-32001,"data":{"code":"UNAUTHORIZED","httpStatus":401,"path":"image.getInfinite"}}}}

**Comment by yokonsan** [comment]
返回写的很明确，让你用开发的 API 去抓，之前的接口限制了
